#ifndef TEXTURE_CONFIG__H
#define TEXTURE_CONFIG__H

enum ImageType
{
	IMAGE_TYPE_1D,
	IMAGE_TYPE_2D,
	IMAGE_TYPE_3D,
	IMAGE_TYPE_CUBE,
	IMAGE_TYPE_MAX_ENUM
};

enum WrapMode
{
	WRAP_MODE_REPEAT,
	WRAP_MODE_MIRRORED_REPEAT,
	WRAP_MODE_CLAMP_TO_EDGE,
	WRAP_MODE_MIRRORED_CLAMP_TO_EDGE,
	WRAP_MODE_CLAMP_TO_BORDER,
	WRAP_MODE_MAX_ENUM
};

enum ImageFilter
{
	FILTER_NEAREST,
	FILTER_LINEAR,
	FILTER_CUBIC,
	FILTER_MAX_ENUM
};

enum MipMapFilter
{
	MIPMAP_FILTER_NEAREST,
	MIPMAP_FILTER_LINEAR,
	MIPMAP_FILTER_MAX_ENUM
};

enum ImageFormat
{
	IMAGE_FORMAT_R8G8B8A8,
	IMAGE_FORMAT_R8G8B8,
	IMAGE_FORMAT_R8G8,
	IMAGE_FORMAT_R8,
	IMAGE_FORMAT_MAX_ENUM
};

struct TextureConfig
{
	ImageFormat format = IMAGE_FORMAT_R8G8B8A8;
	ImageType type = IMAGE_TYPE_2D;
	WrapMode wrapMode = WRAP_MODE_REPEAT;
	ImageFilter filter = FILTER_NEAREST;
	MipMapFilter mipMapFilter = MIPMAP_FILTER_NEAREST;
	bool sRGB = true;
	bool mipmap = true;
};

#endif